# Generated by Django 3.0.6 on 2020-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.TextField()),
                ('country', models.TextField()),
                ('os', models.TextField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField(null=True)),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
        ),
    ]
