# Generated by Django 3.0.6 on 2020-05-13 19:21
import csv
from urllib.request import urlopen
from urllib.parse import unquote
from django.db import migrations

def load_data(apps, schema_editor):
    Metric = apps.get_model('marketing','Metric')
    url = "https://gist.githubusercontent.com/kotik/3baa5f53997cce85cc0336cb1256ba8b/raw/3c2a590b9fb3e9c415a99e56df3ddad5812b292f/dataset.csv"
    response = urlopen(unquote(url))
    with urlopen(url) as f:
        metrics = []
        csv_string = f.read().decode('utf-8')
        csv_reader = csv.DictReader(csv_string.splitlines())
        for row in csv_reader:
            metric = Metric(date=row['date'], 
                channel = row['channel'],
                country = row['country'],
                os = row['os'],
                impressions = row['impressions'],
                clicks = row['clicks'],
                installs = row['installs'],
                spend = row['spend'],
                revenue = row['revenue'])
            
            metrics.append(metric)
    Metric.objects.bulk_create(metrics)

def reverse_func(apps, schema_editor):
    Metric = apps.get_model("marketing", "Metric")

    Metric.objects.all().delete()

  
class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_func)
    ]
